PRODUCT_PACKAGES += $(FEATURES.PRODUCT_PACKAGES)

PRODUCT_PROPERTY_OVERRIDES += $(FEATURES.PRODUCT_PROPERTY_OVERRIDES)

PRODUCT_PACKAGE_OVERLAYS := $(FEATURES.PRODUCT_PACKAGE_OVERLAYS) $(PRODUCT_PACKAGE_OVERLAYS)

PRODUCT_PACKAGES += $(FEATURES.PRODUCT_ADDON_PACKAGES)

LOCAL_BOOT_JARS := $(PRODUCT_BOOT_JARS)
include $(SRC_TARGET_DIR)/product/full_base.mk
PRODUCT_BOOT_JARS += $(LOCAL_BOOT_JARS)
LOCAL_BOOT_JARS :=
